import { FunctionComponent, PropsWithChildren } from "react";
import Head from "next/head";
import { Footer } from "@/components/base";
import Header from "@/components/base/header";

const Root: FunctionComponent<PropsWithChildren> = ({
  children,
}: PropsWithChildren) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <main className="min-h-screen border border-red-50">{children}</main>
        <Footer />
      </div>
    </>
  );
};

export default Root;
