version: 2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

updates:
- package-ecosystem: yarn
  directory: '/'
  target-branch: 'main'
  schedule:
    interval: monthly
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - fransfilastap
  assignees:
    - fransfilastap
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
